### PR TITLE
menus: Fix display custom menu(for macOS compatibility).

### PR DESCRIPTION
**Pull request by YongHaoWu**

### CODE REVIEW

**Comment by YongHaoWu** [comment]
@sainnhe  Plz review this, thx.

**Comment by sainnhe** [comment]
Thank you for the fix!

**Comment by YongHaoWu** [comment]
@sainnhe  Hey, 

`target=$(printf "%s\n[cancel]" "$front_end_list" | eval "$CURRENT_DIR/.fzf-tmux $TMUX_FZF_OPTIONS" | grep -o '^[^[:blank:]]*')` 's `| grep -o '^[^[:blank:]]*'` does not have special consideration, correct?

**Comment by sainnhe** [comment]
I've forgotten it honestly, but looks like it's no problem to remove the code.

**Pull request merged**
