### PR TITLE
add TMUX_FZF_WINDOW_FILTER

### PR DESCRIPTION
**Pull request by aacebedo**
I needed to be able to filter the window by session as if display all of them when not filtered and I had twice the windows listed.

### CODE REVIEW

**Comment by aacebedo** [comment]
Ping ?

**Comment by sainnhe** [comment]
Sorry for late reply :(

The code LGTM. Could you add some related docs to README?

**Comment by aacebedo** [comment]
Thanks for reviewing !
I added something in the README, tell me if it is ok for you.

**Comment by sainnhe** [comment]
LGTM. Thanks for your contribution!

**Pull request merged**
